server:
  port: 9999

# ===== Spring配置(数据源) ===== #
spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/runner?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
#    password: ENC(LCqtEKNdLucRK9sHoaREFA==)
  jackson:
    default-property-inclusion: non-null

# ===== Swagger配置 ===== #
swagger:
  enable: true

# ===== Snowflake配置 ===== #
snowflake: 
  workerId: 0
  centerId: 0
